server:
  port: 8080
  servlet:
    context-path: /

app:
  name: main-service

stats-server:
  url: http://localhost:9090

spring:
  profiles:
    active: default,ci,test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ewm
    username: test
    password: test

  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
        hibernate.format_sql: true
    properties:
      hibernate.format_sql: true
    sql.init.mode: always
